In [27]:
import numpy as np
import pandas as pd
import torch

In [28]:
x=torch.empty(3,5)
x

tensor([[1.3570e-14, 1.0899e+27, 1.2712e+31, 7.6814e+31, 3.8946e+21],
        [4.4650e+30, 1.7590e+22, 2.4176e-12, 2.6209e+20, 4.1641e+12],
        [8.9625e-01, 7.9309e+34, 7.9439e+08, 3.2604e-12, 7.3113e+34]])

In [29]:
torch.randn(5,3)

tensor([[-0.2945,  0.0324,  1.0855],
        [-1.8957, -1.2575, -1.4808],
        [ 0.5408, -0.0885, -1.1317],
        [-0.2204, -0.2654, -0.7563],
        [ 0.0587, -0.0081, -0.0218]])

In [30]:
x=torch.zeros(5,3)
x.shape

torch.Size([5, 3])

In [31]:
y=torch.zeros_like(torch.tensor(x))
y

C:\Users\sunyu\AppData\Local\Temp\ipykernel_11476\2705283038.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y=torch.zeros_like(torch.tensor(x))


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [32]:
x=torch.randn(4,4)
x.size()
x.view(16)

tensor([ 0.6808, -0.2894, -0.9267, -0.4103,  0.9335,  0.8580, -0.6494, -0.3313,
         0.8136,  0.5357, -0.4031, -0.0750, -1.4005, -1.5039,  2.1590,  0.4060])

In [33]:
x_cp=torch.rand(3,5).clone().view(-1,3)
x_cp

tensor([[0.0342, 0.3521, 0.5508],
        [0.8416, 0.4749, 0.8930],
        [0.8862, 0.7626, 0.6950],
        [0.0454, 0.1142, 0.9347],
        [0.7405, 0.6293, 0.5932]])

In [34]:
x=torch.randn(1)
x.item()

-0.4343627691268921

In [35]:
x.view(-1,8)

RuntimeError: shape '[-1, 8]' is invalid for input of size 1

In [ ]:
x=torch.arange(1,3).view(1,2)
y=torch.arange(1,4).view(3,1)
x+y

In [ ]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_1=id(y)
y=x+y
id(y)==id_1

In [ ]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_1=id(y)
y[:]=x+y
id(y)==id_1

In [ ]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to('cpu'))

In [ ]:
a=np.arange(12)
b=torch.from_numpy(a)
type(a),type(b)

In [ ]:
a=torch.ones(5,3)
b=a.numpy()
b

In [ ]:
import numpy as np
a=np.ones([5,2])
b=torch.from_numpy(a)
b

In [ ]:
x=torch.randn(3,4,requires_grad=True)
x

In [ ]:
b=torch.randn(3,4,requires_grad=True)
b

In [ ]:
t=x+b
t

In [ ]:
y=t.sum()
y

In [ ]:
y.backward()

In [ ]:
b.grad

In [ ]:
x.requires_grad,b.requires_grad,t.requires_grad,y.requires_grad

In [ ]:
x=torch.randn(1)
b=torch.randn(1,requires_grad=True)
w=torch.randn(1,requires_grad=True)
y=w*x
z=y+b

In [ ]:
x.requires_grad,w.requires_grad,b.requires_grad,y.requires_grad,z.requires_grad

In [ ]:
x.is_leaf,y.is_leaf

In [ ]:
# z.backward(retain_graph=True)
z.backward()

In [ ]:
x

In [ ]:
w.grad,b.grad

In [ ]:
x=[i for i in range(11)]
x_train=np.array(x,dtype=np.float32)
x_train=x_train.reshape(-1,1)
x_train.shape

In [ ]:
y=[i*2+1 for i in range(11)]
y_train=np.array(y,dtype=np.float32)
y_train=y_train.reshape(-1,1)
y_train.shape

In [ ]:
import torch
import torch.nn as nn
class LinearRegressionModel(nn.Module):
    def __init__(self,input_dim,output_dim):
        super(LinearRegressionModel,self).__init__()
        self.linear=nn.Linear(input_dim,output_dim)
    def forward(self,x):
        out=self.linear(x)
        return out

In [ ]:
input_dim=1
output_dim=1

model=LinearRegressionModel(input_dim,output_dim)
device=torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

In [ ]:
model

In [ ]:
epochs=10000
learning_rate=0.01
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
criterion=nn.MSELoss()

In [ ]:
for epoch in range(epochs):
    epoch+=1

    inputs=torch.from_numpy(x_train).to(device)
    labels=torch.from_numpy(y_train).to(device)

    optimizer.zero_grad()

    outputs=model(inputs)

    loss=criterion(outputs,labels)

    loss.backward()

    optimizer.step()

    if epoch %50==0:
        print(loss.item())

In [ ]:
# pre=model(torch.from_numpy(x_train).requires_grad_()).data
# pre

pre = model(inputs).cpu().detach().numpy()
pre

In [ ]:
import os

In [51]:
import os
import pandas as pd
data_dir = '../data_struct/data'
if not os.path.exists(data_dir):
    os.makedirs(data_dir)

data_file = os.path.join(data_dir, 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [52]:
data=pd.read_csv(data_file)
data.columns=['NumRooms','Alley','Price']
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [53]:
data['NumRooms'].fillna(data['NumRooms'].mean(),inplace=True)
data


NumRooms Alley   Price
0       3.0  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       3.0   NaN  140000

In [54]:
k=pd.get_dummies(data.Alley,dummy_na=True)
k
data=data.join(k)
data

NumRooms Alley   Price  Pave  NaN
0       3.0  Pave  127500     1    0
1       2.0   NaN  106000     0    1
2       4.0   NaN  178100     0    1
3       3.0   NaN  140000     0    1

In [55]:
data=data.drop('Alley',axis=1,inplace=True)
data

NumRooms   Price  Pave  NaN
0       3.0  127500     1    0
1       2.0  106000     0    1
2       4.0  178100     0    1
3       3.0  140000     0    1

In [56]:
outputs=data.Price
data.drop('Price',axis=1,inplace=True)
outputs,data

(0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64,
    NumRooms  Pave  NaN
 0       3.0     1    0
 1       2.0     0    1
 2       4.0     0    1
 3       3.0     0    1)

In [58]:
x,y=torch.tensor(data.values),torch.tensor(outputs.values)
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))